### ISSUE TITLE
time-stamp dependency missing 

### ISSUE THREAD

**Issue by aalteirac** [stefanwalther/sense-go#30]
I'm running node 4.4.7 and after npm install -g sense-go I've got a missing module error:
module.js:327
    throw err;
    ^

Error: Cannot find module 'time-stamp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\aai\AppData\Roaming\npm\node_modules\sense-go\bin\log.js:4:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

after adding this module it runs fine.

**Comment by stefanwalther** [comment]
~~Hmmm, that's pretty weird since `time-stamp` is one of the declared dependencies in `package.json` (see [here](https://github.com/stefanwalther/sense-go/blob/master/package.json#L91)).~~

~~Can you tell me which node.js version you are using. Furthermore, which version of sense-go are you using (just tell me the version in package.json).~~

Thx for reporting, found it, was a typo: installed `timestamp`, were using `time-stamp` ... will upload a fix ASAP.
